version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.httpd
    ports:
      - "80:80"
    container_name: apache_web
    networks:
      - studentapp-net

  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_DATABASE: studentapp
    ports:
      - "3306:3306"
    container_name: mysql_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - studentapp-net

  app:
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    ports:
      - "8080:8080"
    container_name: tomcat_app
    depends_on:
      - db
    networks:
      - studentapp-net

volumes:
  db_data:

networks:
  studentapp-net:
    driver: bridge
